import type { ModulePlan } from '@/types/tmplan'

const now = new Date().toISOString()

// ============================================================
// 博客系统 mock data
// ============================================================
const blogSystemModules: ModulePlan[] = [
  {
    module: '用户认证',
    slug: 'user-auth',
    layer: 'implementation',
    status: 'completed',
    depends_on: [],
    decision_refs: [3],
    overview: '使用NextAuth.js实现GitHub OAuth登录',
    priority: 'high',
    estimated_hours: null,
    created_at: now,
    updated_at: now,
    tasks: [
      {
        id: 'auth-01',
        title: '安装配置NextAuth',
        status: 'completed',
        depends_on: [],
        detail: '安装next-auth并配置GitHub OAuth Provider和Supabase Adapter',
        files_to_create: ['app/api/auth/[...nextauth]/route.ts', 'lib/auth.ts'],
        files_to_modify: [],
        acceptance_criteria: ['访问/api/auth/signin显示GitHub登录按钮'],
      },
      {
        id: 'auth-02',
        title: '创建用户数据表',
        status: 'completed',
        depends_on: ['auth-01'],
        detail: '在Supabase中创建users、accounts、sessions表的迁移文件',
        files_to_create: ['supabase/migrations/001_create_auth_tables.sql'],
        files_to_modify: [],
        acceptance_criteria: ['运行supabase db push后表创建成功'],
      },
      {
        id: 'auth-03',
        title: '登录/登出UI',
        status: 'completed',
        depends_on: ['auth-01', 'auth-02'],
        detail: '创建登录按钮、用户菜单组件，集成到顶部导航栏',
        files_to_create: ['components/auth/sign-in-button.tsx', 'components/auth/user-menu.tsx'],
        files_to_modify: [],
        acceptance_criteria: ['未登录用户访问/dashboard被重定向到登录页'],
      },
    ],
  },
  {
    module: '博客CRUD',
    slug: 'blog-crud',
    layer: 'implementation',
    status: 'in_progress',
    depends_on: ['user-auth'],
    decision_refs: [4],
    overview: '实现文章的增删改查功能',
    priority: 'high',
    estimated_hours: null,
    created_at: now,
    updated_at: now,
    tasks: [
      {
        id: 'blog-01',
        title: '创建数据模型',
        status: 'completed',
        depends_on: [],
        detail: '创建文章、标签的数据库表结构和迁移文件',
        files_to_create: ['supabase/migrations/002_create_blog_tables.sql'],
        files_to_modify: [],
        acceptance_criteria: ['posts和tags表创建成功'],
      },
      {
        id: 'blog-02',
        title: '实现API路由',
        status: 'completed',
        depends_on: ['blog-01'],
        detail: '实现/api/posts的CRUD接口',
        files_to_create: ['app/api/posts/route.ts'],
        files_to_modify: [],
        acceptance_criteria: ['API支持文章的增删改查'],
      },
      {
        id: 'blog-03',
        title: '文章列表页面',
        status: 'in_progress',
        depends_on: ['blog-02'],
        detail: '展示所有文章的列表页面，支持分页和标签筛选',
        files_to_create: ['app/posts/page.tsx'],
        files_to_modify: [],
        acceptance_criteria: ['文章列表正确展示'],
      },
      {
        id: 'blog-04',
        title: '文章编辑器',
        status: 'pending',
        depends_on: ['blog-02'],
        detail: 'Markdown编辑器组件，支持实时预览',
        files_to_create: ['components/blog/editor.tsx'],
        files_to_modify: [],
        acceptance_criteria: ['编辑器支持Markdown语法'],
      },
      {
        id: 'blog-05',
        title: '文章详情页面',
        status: 'pending',
        depends_on: ['blog-03'],
        detail: '文章阅读页面，渲染Markdown内容',
        files_to_create: ['app/posts/[id]/page.tsx'],
        files_to_modify: [],
        acceptance_criteria: ['文章详情正确渲染'],
      },
    ],
  },
  {
    module: '搜索功能',
    slug: 'search',
    layer: 'implementation',
    status: 'pending',
    depends_on: ['blog-crud'],
    decision_refs: [5],
    overview: '基于PostgreSQL全文搜索实现文章搜索',
    priority: 'medium',
    estimated_hours: null,
    created_at: now,
    updated_at: now,
    tasks: [
      {
        id: 'search-01',
        title: '全文搜索配置',
        status: 'pending',
        depends_on: [],
        detail: '配置PostgreSQL全文搜索索引和中文分词',
        files_to_create: ['supabase/migrations/003_search_index.sql'],
        files_to_modify: [],
        acceptance_criteria: ['全文搜索索引创建成功'],
      },
      {
        id: 'search-02',
        title: '搜索API',
        status: 'pending',
        depends_on: ['search-01'],
        detail: '实现/api/search接口',
        files_to_create: ['app/api/search/route.ts'],
        files_to_modify: [],
        acceptance_criteria: ['搜索API返回正确结果'],
      },
      {
        id: 'search-03',
        title: '搜索UI',
        status: 'pending',
        depends_on: ['search-02'],
        detail: '搜索框和搜索结果展示组件',
        files_to_create: ['components/search/search-bar.tsx'],
        files_to_modify: [],
        acceptance_criteria: ['搜索框输入后展示结果'],
      },
    ],
  },
  {
    module: '评论功能',
    slug: 'comments',
    layer: 'implementation',
    status: 'pending',
    depends_on: ['blog-crud'],
    decision_refs: [6],
    overview: '自建评论系统，存储在Supabase中',
    priority: 'medium',
    estimated_hours: null,
    created_at: now,
    updated_at: now,
    tasks: [
      {
        id: 'comment-01',
        title: '评论数据表',
        status: 'pending',
        depends_on: [],
        detail: '创建评论表结构和RLS策略',
        files_to_create: ['supabase/migrations/004_create_comments.sql'],
        files_to_modify: [],
        acceptance_criteria: ['comments表创建成功'],
      },
      {
        id: 'comment-02',
        title: '评论API',
        status: 'pending',
        depends_on: ['comment-01'],
        detail: '实现/api/comments的CRUD接口',
        files_to_create: ['app/api/comments/route.ts'],
        files_to_modify: [],
        acceptance_criteria: ['评论API支持增删改查'],
      },
      {
        id: 'comment-03',
        title: '评论组件',
        status: 'pending',
        depends_on: ['comment-02'],
        detail: '评论列表和评论输入框组件',
        files_to_create: ['components/comments/comment-list.tsx'],
        files_to_modify: [],
        acceptance_criteria: ['评论列表正确展示'],
      },
      {
        id: 'comment-04',
        title: '评论集成',
        status: 'pending',
        depends_on: ['comment-03'],
        detail: '将评论组件集成到文章详情页',
        files_to_create: [],
        files_to_modify: ['app/posts/[id]/page.tsx'],
        acceptance_criteria: ['文章详情页显示评论区'],
      },
    ],
  },
]

// ============================================================
// Todo应用 mock data
// ============================================================
const todoAppModules: ModulePlan[] = [
  {
    module: '数据模型',
    slug: 'data-model',
    layer: 'implementation',
    status: 'completed',
    depends_on: [],
    decision_refs: [1],
    overview: '使用 localStorage 存储待办事项数据',
    priority: 'high',
    estimated_hours: null,
    created_at: now,
    updated_at: now,
    tasks: [
      {
        id: 'dm-01',
        title: '定义Todo类型',
        status: 'completed',
        depends_on: [],
        detail: '定义 Todo 接口和状态枚举',
        files_to_create: ['types/todo.ts'],
        files_to_modify: [],
        acceptance_criteria: ['类型定义完整'],
      },
      {
        id: 'dm-02',
        title: '实现存储层',
        status: 'completed',
        depends_on: ['dm-01'],
        detail: '封装 localStorage 的读写操作',
        files_to_create: ['lib/storage.ts'],
        files_to_modify: [],
        acceptance_criteria: ['数据持久化正常'],
      },
    ],
  },
  {
    module: '基础CRUD',
    slug: 'basic-crud',
    layer: 'implementation',
    status: 'in_progress',
    depends_on: ['data-model'],
    decision_refs: [2],
    overview: '实现待办事项的增删改查',
    priority: 'high',
    estimated_hours: null,
    created_at: now,
    updated_at: now,
    tasks: [
      {
        id: 'crud-01',
        title: '添加待办',
        status: 'completed',
        depends_on: [],
        detail: '输入框和添加按钮组件',
        files_to_create: ['components/todo-input.tsx'],
        files_to_modify: [],
        acceptance_criteria: ['可以添加新待办'],
      },
      {
        id: 'crud-02',
        title: '待办列表',
        status: 'in_progress',
        depends_on: ['crud-01'],
        detail: '展示所有待办事项的列表',
        files_to_create: ['components/todo-list.tsx'],
        files_to_modify: [],
        acceptance_criteria: ['列表正确展示'],
      },
      {
        id: 'crud-03',
        title: '删除和编辑',
        status: 'pending',
        depends_on: ['crud-02'],
        detail: '支持删除和内联编辑待办',
        files_to_create: [],
        files_to_modify: ['components/todo-list.tsx'],
        acceptance_criteria: ['删除和编辑功能正常'],
      },
    ],
  },
  {
    module: '拖拽排序',
    slug: 'drag-sort',
    layer: 'implementation',
    status: 'pending',
    depends_on: ['basic-crud'],
    decision_refs: [3],
    overview: '使用 dnd-kit 实现拖拽排序',
    priority: 'medium',
    estimated_hours: null,
    created_at: now,
    updated_at: now,
    tasks: [
      {
        id: 'drag-01',
        title: '集成dnd-kit',
        status: 'pending',
        depends_on: [],
        detail: '安装并配置 dnd-kit 拖拽库',
        files_to_create: ['lib/dnd-config.ts'],
        files_to_modify: [],
        acceptance_criteria: ['拖拽库集成成功'],
      },
      {
        id: 'drag-02',
        title: '拖拽交互',
        status: 'pending',
        depends_on: ['drag-01'],
        detail: '为待办列表添加拖拽排序功能',
        files_to_create: [],
        files_to_modify: ['components/todo-list.tsx'],
        acceptance_criteria: ['拖拽排序正常工作'],
      },
    ],
  },
]

// ============================================================
// 电商平台 mock data
// ============================================================
const ecommerceModules: ModulePlan[] = [
  {
    module: '用户系统',
    slug: 'user-system',
    layer: 'implementation',
    status: 'completed',
    depends_on: [],
    decision_refs: [1],
    overview: '用户注册、登录和权限管理',
    priority: 'high',
    estimated_hours: null,
    created_at: now,
    updated_at: now,
    tasks: [
      {
        id: 'user-01',
        title: '注册登录',
        status: 'completed',
        depends_on: [],
        detail: '实现邮箱注册和JWT登录',
        files_to_create: ['app/api/auth/register/route.ts', 'app/api/auth/login/route.ts'],
        files_to_modify: [],
        acceptance_criteria: ['注册登录流程正常'],
      },
      {
        id: 'user-02',
        title: '角色权限',
        status: 'completed',
        depends_on: ['user-01'],
        detail: '实现商户和买家角色区分',
        files_to_create: ['lib/rbac.ts'],
        files_to_modify: [],
        acceptance_criteria: ['权限控制正常'],
      },
    ],
  },
  {
    module: '商品管理',
    slug: 'product-mgmt',
    layer: 'implementation',
    status: 'completed',
    depends_on: ['user-system'],
    decision_refs: [2],
    overview: '商品的增删改查和分类管理',
    priority: 'high',
    estimated_hours: null,
    created_at: now,
    updated_at: now,
    tasks: [
      {
        id: 'prod-01',
        title: '商品数据模型',
        status: 'completed',
        depends_on: [],
        detail: '创建商品表和分类表',
        files_to_create: ['prisma/schema.prisma'],
        files_to_modify: [],
        acceptance_criteria: ['数据模型完整'],
      },
      {
        id: 'prod-02',
        title: '商品CRUD API',
        status: 'completed',
        depends_on: ['prod-01'],
        detail: '实现商品的增删改查接口',
        files_to_create: ['app/api/products/route.ts'],
        files_to_modify: [],
        acceptance_criteria: ['API功能正常'],
      },
      {
        id: 'prod-03',
        title: '商品列表页',
        status: 'completed',
        depends_on: ['prod-02'],
        detail: '商品展示页面，支持筛选和搜索',
        files_to_create: ['app/products/page.tsx'],
        files_to_modify: [],
        acceptance_criteria: ['商品列表正确展示'],
      },
    ],
  },
  {
    module: '购物车',
    slug: 'shopping-cart',
    layer: 'implementation',
    status: 'in_progress',
    depends_on: ['product-mgmt'],
    decision_refs: [3],
    overview: '购物车功能，支持数量修改和商品选择',
    priority: 'high',
    estimated_hours: null,
    created_at: now,
    updated_at: now,
    tasks: [
      {
        id: 'cart-01',
        title: '购物车状态管理',
        status: 'completed',
        depends_on: [],
        detail: '使用 Zustand 管理购物车状态',
        files_to_create: ['stores/cart-store.ts'],
        files_to_modify: [],
        acceptance_criteria: ['状态管理正常'],
      },
      {
        id: 'cart-02',
        title: '购物车页面',
        status: 'in_progress',
        depends_on: ['cart-01'],
        detail: '购物车列表页面，支持数量修改',
        files_to_create: ['app/cart/page.tsx'],
        files_to_modify: [],
        acceptance_criteria: ['购物车页面功能正常'],
      },
      {
        id: 'cart-03',
        title: '加入购物车按钮',
        status: 'pending',
        depends_on: ['cart-01'],
        detail: '在商品详情页添加加入购物车按钮',
        files_to_create: [],
        files_to_modify: ['app/products/[id]/page.tsx'],
        acceptance_criteria: ['加入购物车功能正常'],
      },
    ],
  },
  {
    module: '订单系统',
    slug: 'order-system',
    layer: 'implementation',
    status: 'pending',
    depends_on: ['shopping-cart'],
    decision_refs: [4],
    overview: '订单创建、支付和状态管理',
    priority: 'high',
    estimated_hours: null,
    created_at: now,
    updated_at: now,
    tasks: [
      {
        id: 'order-01',
        title: '订单数据模型',
        status: 'pending',
        depends_on: [],
        detail: '创建订单表和订单项表',
        files_to_create: ['prisma/migrations/create_orders.sql'],
        files_to_modify: [],
        acceptance_criteria: ['订单表创建成功'],
      },
      {
        id: 'order-02',
        title: '下单流程',
        status: 'pending',
        depends_on: ['order-01'],
        detail: '从购物车到确认订单的流程',
        files_to_create: ['app/checkout/page.tsx'],
        files_to_modify: [],
        acceptance_criteria: ['下单流程正常'],
      },
      {
        id: 'order-03',
        title: '订单列表',
        status: 'pending',
        depends_on: ['order-02'],
        detail: '用户订单列表和订单详情页',
        files_to_create: ['app/orders/page.tsx'],
        files_to_modify: [],
        acceptance_criteria: ['订单列表正确展示'],
      },
    ],
  },
  {
    module: '支付集成',
    slug: 'payment',
    layer: 'implementation',
    status: 'pending',
    depends_on: ['order-system'],
    decision_refs: [5],
    overview: '集成支付宝/微信支付',
    priority: 'medium',
    estimated_hours: null,
    created_at: now,
    updated_at: now,
    tasks: [
      {
        id: 'pay-01',
        title: '支付SDK集成',
        status: 'pending',
        depends_on: [],
        detail: '集成支付宝SDK并配置回调',
        files_to_create: ['lib/payment.ts', 'app/api/payment/callback/route.ts'],
        files_to_modify: [],
        acceptance_criteria: ['支付SDK配置成功'],
      },
      {
        id: 'pay-02',
        title: '支付页面',
        status: 'pending',
        depends_on: ['pay-01'],
        detail: '支付确认页面和支付结果页',
        files_to_create: ['app/payment/page.tsx'],
        files_to_modify: [],
        acceptance_criteria: ['支付流程正常'],
      },
    ],
  },
  {
    module: '商户后台',
    slug: 'merchant-admin',
    layer: 'implementation',
    status: 'pending',
    depends_on: ['product-mgmt', 'order-system'],
    decision_refs: [6],
    overview: '商户管理后台，查看订单和管理商品',
    priority: 'medium',
    estimated_hours: null,
    created_at: now,
    updated_at: now,
    tasks: [
      {
        id: 'admin-01',
        title: '后台布局',
        status: 'pending',
        depends_on: [],
        detail: '商户后台的整体布局和导航',
        files_to_create: ['app/admin/layout.tsx'],
        files_to_modify: [],
        acceptance_criteria: ['后台布局正常'],
      },
      {
        id: 'admin-02',
        title: '订单管理',
        status: 'pending',
        depends_on: ['admin-01'],
        detail: '商户查看和处理订单',
        files_to_create: ['app/admin/orders/page.tsx'],
        files_to_modify: [],
        acceptance_criteria: ['订单管理功能正常'],
      },
    ],
  },
]

// ============================================================
// 按项目ID获取对应的mock数据
// ============================================================
export const mockProjectModules: Record<string, ModulePlan[]> = {
  'blog-system': blogSystemModules,
  'todo-app': todoAppModules,
  'ecommerce': ecommerceModules,
}

// 保留向后兼容
export const mockModules = blogSystemModules
